# Generated by Django 3.1 on 2020-08-26 17:08

from django.db import migrations, models
import main.util


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalimage',
            options={'verbose_name': 'Дополнительная фотография', 'verbose_name_plural': 'Дополнительные фотографии'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={'verbose_name': 'Рубрика', 'verbose_name_plural': 'Рубрики'},
        ),
        migrations.AddField(
            model_name='editarticle',
            name='help_text',
            field=models.CharField(max_length=200, null=True, verbose_name='Кратко объясните изменения'),
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(upload_to=main.util.get_timestamp_path, verbose_name='Фотография'),
        ),
    ]
